### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by xsqwx1x** [PanagiotisIatrou/chess-auto-bot#57]
when i click on the "Open Browser" button, nothing happens, it shows "Opening Browser..." endlessly. What should I do? I chose stockfish and cores and memory, but nothing happens.

**Comment by NistNerj** [comment]
Hello. I also suffered with this problem. It turned out to be quite simple.

You need to run: pip install --upgrade webdriver_manager

Next go to c:\Users\~User_Name\AppData\Roaming\Python\~python_version~\site-packages\

And copy the folders: webdriver_manager, webdriver_manager-4.0.1.dist-info

And paste them into the ~\chess-auto-bot-main\venv\Lib\site-packages\ directory
Having previously deleted the old folders (for me these were the folders: webdriver_manager, webdriver_manager-3.8.6)

After these steps, restart the program and open your browser. Everything worked for me.

Sorry for my English, I'm from Russia and used a translator.

**Comment by PanagiotisIatrou** [comment]
Hello @xsqwx1x,

Thanks for pointing out, I fixed it in the latest commit 9b70ec15a9912799430897a89f5a1acf47bc62fe
