### ISSUE TITLE
Last update bug.

### ISSUE THREAD

**Issue by vioo-bkp** [PanagiotisIatrou/chess-auto-bot#9]
Hello @PanagiotisIatrou, in the last update the bot no longer makes moves on the board. Regardless of whether it is set to manual or not. Arrows appear outside the boards.
Specs:
Win 10
Python 3.10
Default option bot (no modification).
Attachments:

Autoplay:
![Untitled](https://user-images.githubusercontent.com/59666442/209876417-8929cbfc-18f4-4996-9a49-e96c9884a328.png)
Manual:
![Untitled1](https://user-images.githubusercontent.com/59666442/209876427-8a096717-0459-4095-8a3e-4e10260bc578.png)

**Comment by PanagiotisIatrou** [comment]
Hello @vioo-bkp. Thanks for the feedback. This is odd, I did a clean installation from the steps in the README and it worked just fine on Windows 10 with python 3.10. Perhaps take a look at this issue https://github.com/PanagiotisIatrou/chess-auto-bot/issues/2 and make sure the scaling on windows is set to 100%.

Other than that the GUI itself looks a bit weird too, the right panel with the moves list should be larger. Did you do a clean installation following the README since the last update or did you pull the changes? If so can you try with a clean installation?

**Comment by vioo-bkp** [comment]
Hello there! Forgive me for being late @PanagiotisIatrou. After I performed a clean installation and reinstalled python 3.10, the problem disappeared and the code works. It was weird because the scaling was set to 100%. Probably because I use an ultra-wide 32:9 monitor on which I increased the font? Everything seems normal now.
